import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/prisma'

export async function POST() {
  try {
    const session = await getServerSession(authOptions)
    
    if (!session || !session.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const userId = (session.user as any).id
    const prismaClient = await prisma

    const profile = await prismaClient.influencerProfile.findUnique({
      where: { userId },
      include: {
        user: true,
        socialMetrics: {
          orderBy: { fetchedAt: 'desc' },
          take: 1,
        },
      },
    })

    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 })
    }

    // Generate HTML for media kit
    const totalFollowers = profile.followers ? 
      Object.values(profile.followers as Record<string, number>).reduce((a: number, b: number) => a + b, 0) : 0

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${profile.user.name} - Media Kit</title>
          <style>
            body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
            h1 { color: #FF6B6B; text-align: center; }
            .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 30px 0; }
            .stat-card { background: #f5f5f5; padding: 20px; border-radius: 8px; text-align: center; }
            .stat-value { font-size: 32px; font-weight: bold; color: #FF6B6B; }
            .stat-label { font-size: 14px; color: #666; margin-top: 5px; }
            .section { margin: 30px 0; }
            .section-title { font-size: 20px; font-weight: bold; margin-bottom: 15px; }
            .niches { display: flex; flex-wrap: wrap; gap: 10px; }
            .niche-tag { background: #FF6B6B; color: white; padding: 8px 16px; border-radius: 20px; font-size: 14px; }
          </style>
        </head>
        <body>
          <h1>${profile.user.name}</h1>
          <p style="text-align: center; color: #666;">Influencer • Content Creator</p>
          
          <div class="stats">
            <div class="stat-card">
              <div class="stat-value">${totalFollowers.toLocaleString()}</div>
              <div class="stat-label">Total Followers</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">${profile.engagementRate.toFixed(1)}%</div>
              <div class="stat-label">Engagement Rate</div>
            </div>
            <div class="stat-card">
              <div class="stat-value">${profile.authenticityScore}/100</div>
              <div class="stat-label">Authenticity Score</div>
            </div>
          </div>
          
          ${profile.bio ? `
            <div class="section">
              <div class="section-title">About</div>
              <p>${profile.bio}</p>
            </div>
          ` : ''}
          
          <div class="section">
            <div class="section-title">Content Categories</div>
            <div class="niches">
              ${profile.niches.map((niche: string) => `<span class="niche-tag">${niche}</span>`).join('')}
            </div>
          </div>
          
          <div class="section">
            <div class="section-title">Social Media</div>
            ${profile.instagramHandle ? `<p><strong>Instagram:</strong> @${profile.instagramHandle}</p>` : ''}
            ${profile.twitterHandle ? `<p><strong>Twitter:</strong> @${profile.twitterHandle}</p>` : ''}
            ${profile.youtubeChannel ? `<p><strong>YouTube:</strong> ${profile.youtubeChannel}</p>` : ''}
          </div>
          
          <div style="text-align: center; margin-top: 50px; color: #999; font-size: 12px;">
            Generated by InfluenceHub • ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `

    // Store media kit
    const mediaKit = await prismaClient.mediaKit.upsert({
      where: { influencerId: profile.id },
      create: {
        influencerId: profile.id,
        html,
        template: 'default',
        pdfUrl: null,
      },
      update: {
        html,
        updatedAt: new Date(),
      },
    })

    // Return shareable link
    const shareableUrl = `${process.env.NEXTAUTH_URL}/mediakit/${mediaKit.id}`

    return NextResponse.json({ 
      success: true,
      url: shareableUrl,
      html
    })
  } catch (error) {
    console.error('Media kit generation error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
